### ISSUE TITLE
Docker Image für Swing GUI

### ISSUE THREAD

**Issue by thebrunner** [oliverbauer/jMIF#24]

**Comment by thebrunner** [comment]
Dockerfile kreieren bzw deklarativ innerhlb der POM im Plugin um die notwendigen externen Abhängigkeiten ins Image zu laden

**Comment by oliverbauer** [comment]
Preference: Dockerfile.

docker build . -t mlt
docker run -i -t mlt

Not yet finished - currently work in progress...:

FROM ubuntu:18.04
MAINTAINER Oliver Bauer <oliver.bauer@tu-dortmund.de>

ENV DEBIAN_FRONTEND=noninteractive
# Solution from https://github.com/phusion/passenger-docker/issues/195:
RUN apt-get update && apt-get install -y tzdata
RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
RUN dpkg-reconfigure --frontend noninteractive tzdata

# TODO Install packages for building melt

ENV HOME /tmp

RUN apt-get install melt -y
RUN apt-get install git -y
RUN apt-get install maven -y
RUN mkdir -p /home/jMIF
# clone locally before invoking the script to build a docker file!!!!
# TODO don't do this... better: clone from started image
COPY jMIF/ /home/jMIF/
WORKDIR /home/jMIF/

# local file!
# TODO better: Download from started image
COPY jdk-14.0.1_linux-x64_bin.tar.gz /home/jMIF/
RUN gunzip jdk-14.0.1_linux-x64_bin.tar.gz
RUN tar -xf jdk-14.0.1_linux-x64_bin.tar
RUN ls -la /home/jMIF/jdk-14.0.1/
ENV JAVA_HOME=/home/jMIF/jdk-14.0.1
# TODO not sure if the following is necessary...
RUN export PATH=$PATH:$JAVA_HOME/bin
RUN mvn clean install -Dmaven.test.skip

WORKDIR /home/jMIF

**Comment by thebrunner** [comment]
- Habe versucht ein Image zu nutzen welchen schon OpenJDK14 beinhaltet
- Maven wird im Image nicht benötigt (wir wollen ja nicht bauen sondern starten ;) )

**Comment by thebrunner** [comment]
fabric8 plugin erstellt die jars im Verzeichnis maven/ innerhalb des Images.
Name der jar und ob sie geshaded ist ist noch nicht bekannt.

**Comment by oliverbauer** [comment]
The provided Dockerfile works at least within Linux. Within Windows i have not tested enough, maybe there is some X-Server necessary.
