### ISSUE TITLE
Using other image / video API than AWT

### ISSUE THREAD

**Issue by thebrunner** [oliverbauer/jMIF#34]
i.e.:
https://www.baeldung.com/java-images
https://www.oracle.com/technetwork/java/javase/tech/media-141984.html

**Comment by oliverbauer** [comment]
What do you think about?
https://github.com/rkalla/imgscalr
It is already included
		<dependency>
			<groupId>org.imgscalr</groupId>
			<artifactId>imgscalr-lib</artifactId>
			<version>4.2</version>
		</dependency>

**Comment by oliverbauer** [comment]
Please provide more hints for working on this topic (small code-snippets of current state and new state)

**Comment by oliverbauer** [comment]
Since no feedback provided i will close this issue
